INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 5, 'F022: DV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 6, 'F023: DV1 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 11, 'F028: RV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 12, 'F029: RV1 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 13, 'F030: SRV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 14, 'F031: SRV1 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 15, 'F032: DP1 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 0, 'F033: VV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 1, 'F034: VV1 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 2, 'F035: GV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 3, 'F036: GV1 Close Open'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 4, 'F037: TP1 Start Failure'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 5, 'F038: EV1 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 6, 'F039: EV1 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 18, 9, 'F042: DP3 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 21, 9, 'F090: LL MFC1 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 21, 12, 'F093: LL MFC2 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 25, 15, 'F160: LL MFC Operating Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 26, 0, 'F161: LL MFC Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 26, 1, 'F162: LL_TR Pressure difference Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 26, 11, 'F172: LL To TR1 Transmission Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 28, 7, 'F200: DP1 Flow Error (X1011)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 28, 10, 'F203: TP1 Pump Flow Error (X1029)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 29, 11, 'F220: LL Guage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 0, 'F000: Emg Off (Interface)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 1, 'F001: Panel Door Emg Off'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 2, 'F002: Emg Off (Handy)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 3, 'F003: System OK Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 4, 'F004: All Cooling Water Stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 5, 'F005: Cool Water Press. Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 6, 'F006: Air Press. Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 7, 'F007: Ar Press. Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 8, 'F008: O2 Press. Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 9, 'F009: N2 Press. Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 10, 'F010: Ch inwall Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 11, 'F011: Door inwall Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 12, 'F012: G1 Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 13, 'F013: G2 Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 14, 'F014: Steer Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 0, 15, 'F015: MH Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 0, 'F016: BG Water Flow Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 1, 'F017: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 2, 'F018: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 3, 'F019: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 4, 'F020: PLC Watch Dog Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 5, 'F021: 01 QJ71LP21 Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 6, 'F022: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 7, 'F023: 03 Q68ADV Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 8, 'F024: 04 Q64AD Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 9, 'F025: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 10, 'F026: 06 Q64DAN Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 11, 'F027: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 12, 'F028: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 13, 'F029: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 14, 'F030: SLOT10 QJ61BT11N Alarm'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 1, 15, 'F031: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 0, 'F032: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 1, 'F033: H Network Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 2, 'F034: H Main Loop Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 3, 'F035: H Sub Loop Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 4, 'F036: CC-Link Offline Unit Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 5, 'F037: CC-Link Input Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 6, 'F038: CC-Link Output Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 7, 'F039: CC-Link Sensor Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 8, 'F040: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 9, 'F041: M.H. Pushup Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 10, 'F042: Charg Pushup Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 11, 'F043: Charg Rotation Link Down'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 12, 'F044: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 13, 'F045: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 14, 'F046: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 2, 15, 'F047: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 0, 'F048: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 1, 'F049: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 2, 'F050: PLC Init Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 3, 'F051: Panel Cooling Fan'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 4, 'F052: Power MC Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 5, 'F053: M.H. Pushup MC Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 6, 'F054: Charg Pushup MC Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 7, 'F055: Charg Rotation MC Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 8, 'F056: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 9, 'F057: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 10, 'F058: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 11, 'F059: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 12, 'F060: M-Power Unit Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 13, 'F061: S-Power Over-heat'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 14, 'F062: Anode Chg Contactor MC Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 3, 15, 'F063: HC Power Error   '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 0, 'F064: Steer Power Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 1, 'F065: G2 Power Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 2, 'F066: HC Power Off'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 3, 'F067: Steer Power Off'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 4, 'F068: G2 Power Off'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 5, 'F069: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 6, 'F070: Discharge Current Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 7, 'F071: Discharge Current Error (Little)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 8, 'F072: MH Low Volt. Error In Discharge'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 9, 'F073: B.G. Current Error S-Power Run'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 10, 'F074: B.G. Current Error M-Power Run'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 11, 'F075: Discharge Current Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 12, 'F076: Discharge High Voltage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 13, 'F077: Gun Cooling Fan Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 14, 'F078: Hearth Cleaner Position Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 4, 15, 'F079: Viewport Position Error in Auto.Coating'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 0, 'F080: Hearth Coil Voltage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 1, 'F081: Steering Coil Voltage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 2, 'F082: G2 Coil Voltage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 3, 'F083: Hearth Coil Current Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 4, 'F084: Steering Coil Current Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 5, 'F085: G2 Coil Current Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 6, 'F086: Gun Ar Flow-Value Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 7, 'F087: Chamber O2 Flow-Value Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 8, 'F088: Chamber Ar Flow-Value Deviation Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 9, 'F089: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 10, 'F090: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 11, 'F091: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 12, 'F092: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 13, 'F093: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 14, 'F094: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 5, 15, 'F095: [BG-E] Resistance out of range'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 0, 'F096: [MH-E] Resistance out of range'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 1, 'F097: [G1-E] Resistance out of range'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 2, 'F098: [G2-E] Resistance out of range'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 3, 'F099: [BG-BGC] Resistanc out of range'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 4, 'F100: S-Power Supply Operating Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 5, 'F101: Gun Auto Ignition Gas-Revision Re-try Failure'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 6, 'F102: Gun Cooling Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 7, 'F103: Pressure break In Discharge'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 8, 'F104: Gun No TB (Zero) in discharge'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 9, 'F105: Gun Auto. Ignition Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 10, 'F106: Gun Auto. Cooling Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 11, 'F107: Discharge Change (BG->MH) Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 12, 'F108: Discharge Change (MH->BG) Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 13, 'F109: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 14, 'F110: MH PushUp unit Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 6, 15, 'F111: Charging PushUp unit Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 0, 'F112: Charging Revolver unit Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 1, 'F113: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 2, 'F114: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 3, 'F115: MH PushUp Unit Response Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 4, 'F116: Charging PushUp Unit Response Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 5, 'F117: Charging Revolver Unit Response Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 6, 'F118: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 7, 'F119: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 8, 'F120: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 9, 'F121: MH PushUp Unit Data Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 10, 'F122: Charging PushUp Unit Data Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 11, 'F123: Charging Revolver Unit Data Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 12, 'F124: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 13, 'F125: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 14, 'F126: MH Position Data recovery writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 7, 15, 'F127: Charging Position Data recovery writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 0, 'F128: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 1, 'F129: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 2, 'F130: MH PushUp Home Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 3, 'F131: MH PushUp Down Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 4, 'F132: MH PushUp Init. Up Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 5, 'F133: MH PushUp Touch Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 6, 'F134: MH PushUp 1 Pitch Action Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 7, 'F135: MH PushUp Home Position Reset Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 8, 'F136: MH PushUp Motor Unit Command Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 9, 'F137: MH PushUp Up Limit Position Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 10, 'F138: MH PushUp Down Limit Position Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 11, 'F139: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 12, 'F140: Charging PushUp Home Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 13, 'F141: Charging PushUp Up Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 14, 'F142: Charging PushUp Down Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 8, 15, 'F143: Charging PushUp Unit Command Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 0, 'F144: Charging PushUp Up-Limit Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 1, 'F145: Charging PushUp Down-Limit Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 2, 'F146: Charging Auto.TB Initial Charge Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 3, 'F147: Charging Auto.TB Charge Action Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 4, 'F148: Charging Auto.MH Load Action Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 5, 'F149: Charging Auto Revolver Detect. Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 6, 'F150: Charging Turn Table CW Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 7, 'F151: Charging Turn Table CCW Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 8, 'F152: Charging Turn Table CW/CCW Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 9, 'F153: Charging Turn Table CW Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 10, 'F154: Charging Turn Table CCW Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 11, 'F155: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 12, 'F156: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 13, 'F157: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 14, 'F158: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 9, 15, 'F159: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 0, 'F160: Charging Gate Linked Auto. Open Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 1, 'F161: Charging Gate Linked Auto. Close Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 2, 'F162: Charging UpGate Open Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 3, 'F163: Charging UpGate Close Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 4, 'F164: Charging LowGate Open Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 5, 'F165: Charging LowGate Close Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 6, 'F166: Charging UpGate Open Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 7, 'F167: Charging UpGate Close Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 8, 'F168: Charging LowGate Open Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 9, 'F169: Charging LowGate Close Not Response'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 10, 'F170: Charging Revolver Home Position Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 11, 'F171: Charging Revolver 1 Pitch Action Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 12, 'F172: Charging Revolver Home Position Sensor Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 13, 'F173: Charging Revolver Home Position Data Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 14, 'F174: Charging Revolver Command Writing Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 10, 15, 'F175: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 0, 'F176: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 1, 'F177: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 2, 'F178: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 3, 'F179: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 4, 'F180: Charging Chamber Vacuum Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 5, 'F181: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 6, 'F182: Charging Chamber Vent Time Out'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 7, 'F183: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 8, 'F184: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 9, 'F185: Pressure break In Discharge'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 10, 'F186: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 11, 'F187: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 12, 'F188: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 13, 'F189: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 14, 'F190: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 11, 15, 'F191: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 0, 'F192: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 1, 'F193: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 2, 'F194: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 3, 'F195: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 4, 'F196: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 5, 'F197: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 6, 'F198: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 7, 'F199: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 8, 'F200: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 9, 'F201: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 10, 'F202: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 11, 'F203: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 12, 'F204: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 13, 'F205: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 14, 'F206: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 12, 15, 'F207: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 0, 'F208: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 1, 'F209: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 2, 'F210: PLC Battery Voltage Low'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 3, 'F211: Chamber Inwall Cooling Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 4, 'F212: Door Inwall Cooling Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 5, 'F213: G1 Cooling Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 6, 'F214: G2 Cooling Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 7, 'F215: Steering Cooling Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 8, 'F216: MH Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 9, 'F217: BG Water Flow Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 10, 'F218: R-Power Panel Fan Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 11, 'F219: Handy Touch Panel Offline'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 12, 'F220: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 13, 'F221: Ignition Time Out Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 14, 'F222: Discharge or MH Voltage Shift Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 13, 15, 'F223: Discharge or Coating Pressure Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 0, 'F224: PCC Chamber Main-valve Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 1, 'F225: Charging Chamber Main-valve Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 2, 'F226: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 3, 'F227: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 4, 'F228: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 5, 'F229: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 6, 'F230: Charging Remaining Less Than 5'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 7, 'F231: Charging unit charging request'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 8, 'F232: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 9, 'F233: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 10, 'F234: Charging TB Detection Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 11, 'F235: Charging Chamber Pressure break Warning'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 12, 'F236: Charg request'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 13, 'F237: Charging Revolver Home position Sensor Warning '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 14, 'F238: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 14, 15, 'F239: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 0, 'F240: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 1, 'F241: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 2, 'F242: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 3, 'F243: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 4, 'F244: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 5, 'F245: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 6, 'F246: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 7, 'F247: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 8, 'F248: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 9, 'F249: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 10, 'F250: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 11, 'F251: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 12, 'F252: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 13, 'F253: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 14, 'F254: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 15, 15, 'F255: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 3, 'F052: GV4 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 4, 'F053: GV4 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 5, 'F054: TP4 Start Failure'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 6, 'F055: EV4 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 7, 'F056: EV4 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 8, 'F057: OP Start Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 9, 'F058: RV4 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 19, 10, 'F059: RV4 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 20, 1, 'F066: VV4 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 20, 2, 'F067: VV4 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 28, 15, 'F208: G1 Flow Error (X1036)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 0, 'F209: G2 Flow Error (X1037)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 1, 'F210: steering coil Flow Er (X1038)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 2, 'F211: Hearth Main Flow Error (X1039)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 3, 'F212: Hearth Beam Flow Error (X103A)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 4, 'F213: Door Inwall Flow Error (X1035)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 5, 'F214: Ch Inwal Flow Error (X103B)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 29, 13, 'F222: TSS Guage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 0, 'F001: Emergency Stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 1, 'F002: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 2, 'F003: All Chamber vacuum process Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 3, 'F004: All Chamber Vent process Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 4, 'F005: All TP Start process Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 5, 'F006: force stop TP4'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 6, 'F007: force stop TP3'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 7, 'F008: force stop TP2'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 8, 'F009: force stop TP1'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 9, 'F010: SHI force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 10, 'F011: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 11, 'F012: EV4 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 12, 'F013: EV3 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 13, 'F014: EV2 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 14, 'F015: EV1 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 15, 'F016: GV4 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 0, 'F017: GV3 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 1, 'F018: GV2 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 2, 'F019: GV1 force stop'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 3, 'F020: Main Water Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 4, 'F021: Main CDA Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 9, 'F026: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 10, 'F027: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 1, 'F050: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 2, 'F051: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 11, 'F060: Upper Gate Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 12, 'F061: Upper Gate Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 13, 'F062: Lower Gate Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 14, 'F063: Lower Gate Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 15, 'F064: TurnTable CW Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 0, 'F065: TurnTable CCW Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 9, 'F074: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 15, 'F080: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 5, 'F086: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 6, 'F087: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 7, 'F088: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 8, 'F089: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 0, 'F097: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 1, 'F098: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 2, 'F099: TR MFC4 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 3, 'F100: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 4, 'F101: Position Controller Failure_A1'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 5, 'F102: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 6, 'F103: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 7, 'F104: Driver Alarm_A1'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 8, 'F105: Position Controller Failure_A2'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 9, 'F106: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 10, 'F107: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 11, 'F108: Driver Alarm_A2'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 12, 'F109: Position Controller Failure_A3'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 13, 'F110: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 14, 'F111: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 15, 'F112: Driver Alarm_A3'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 0, 'F113: Position Controller Failure_A4'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 1, 'F114: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 2, 'F115: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 3, 'F116: Driver Alarm_A4'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 4, 'F117: Position Controller Failure_A5'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 5, 'F118: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 6, 'F119: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 7, 'F120: Driver Alarm_A5'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 8, 'F121: Position Controller Failure_A6'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 9, 'F122: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 10, 'F123: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 11, 'F124: Driver Alarm_A6'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 12, 'F125: Position Controller Failure_A7'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 13, 'F126: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 14, 'F127: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 15, 'F128: Driver Alarm_A7'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 0, 'F129: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 1, 'F130: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 2, 'F131: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 3, 'F132: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 4, 'F133: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 5, 'F134: DP1 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 6, 'F135: DP3 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 7, 'F136: DP2 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 8, 'F137: TP1 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 9, 'F138: TR2 Ch flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 10, 'F139: TP3 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 11, 'F140: TR3 Lid flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 12, 'F141: TR2 Plate flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 13, 'F142: G1 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 14, 'F143: G2 flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 15, 'F144: Steering coil flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 0, 'F145: MH flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 1, 'F146: BG flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 2, 'F147: Door Inwall flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 3, 'F148: Ch Inwall flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 4, 'F149: TP2 Pump flow rate abnormal'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 5, 'F150: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 6, 'F151: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 7, 'F152: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 8, 'F153: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 9, 'F154: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 10, 'F155: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 11, 'F156: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 12, 'F157: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 13, 'F158: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 14, 'F159: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 2, 'F163: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 3, 'F164: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 4, 'F165: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 5, 'F166: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 6, 'F167: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 7, 'F168: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 8, 'F169: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 14, 'F175: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 15, 'F176: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 0, 'F177: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 1, 'F178: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 2, 'F179: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 9, 'F186: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 10, 'F187: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 11, 'F188: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 12, 'F189: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 15, 'F192: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 0, 'F193: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 1, 'F194: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 2, 'F195: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 3, 'F196: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 4, 'F197: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 5, 'F198: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 6, 'F199: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 7, 'F216: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 8, 'F217: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 9, 'F218: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 10, 'F219: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 15, 'F224: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 0, 'F225: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 1, 'F226: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 2, 'F227: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 3, 'F228: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 4, 'F229: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 5, 'F230: BG Mode > 2 hr'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 6, 'F231: Resistance Measurement'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 7, 'F232: Discharge Chg to BG'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 8, 'F233: Discharge Chg to Main'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 9, 'F234: Auto Ignition'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 10, 'F235: Auto Cooling ON'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 11, 'F236: Auto Cooling OFF'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 12, 'F237: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 13, 'F238: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 14, 'F239: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 15, 'F240: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 0, 'F241: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 1, 'F242: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 2, 'F243: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 3, 'F244: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 4, 'F245: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 5, 'F246: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 6, 'F247: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 7, 'F248: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 8, 'F249: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 9, 'F250: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 10, 'F251: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 11, 'F252: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 12, 'F253: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 13, 'F254: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 14, 'F255: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 15, 'F256: '); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 7, 'F024: DV2 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 8, 'F025: DV2 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 7, 'F040: RV3 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 8, 'F041: RV3 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 10, 'F043: GV3 Open'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 11, 'F044: GV3 Close'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 12, 'F045: TP3 Start Failure'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 18, 15, 'F048: DV3 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 0, 'F049: DV3 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 3, 'F068: VV3 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 4, 'F069: VV3 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 21, 1, 'F082: EV3 Open'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 21, 2, 'F083: EV3 Close'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 21, 11, 'F092: TR MFC1 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 21, 14, 'F095: TR MFC2 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 21, 15, 'F096: TR MFC3 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 26, 9, 'F170: TR1 To LL Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 26, 10, 'F171: TR MFC Operating Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 26, 12, 'F173: TR2 To TR1 Transmission Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 26, 13, 'F174: TR1 Tray Position Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 3, 'F180: TR1 To TR2 Transmission Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 4, 'F181: TR2 To TR3 Transmission Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 5, 'F182: TR3 To TR2 Transmission Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 6, 'F183: UL and TR Pressure difference Errror'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 7, 'F184: TR3 Tray Position Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 27, 8, 'F185: TR3 To UL Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 28, 8, 'F201: DP3 Flow Error (X1031)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 28, 11, 'F204: TR CH Flow Error (X105B)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 28, 12, 'F205: TR TP Pump Flow Error (X103E)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 28, 13, 'F206: TR Lid Flow Error (X105C)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 28, 14, 'F207: TR2 Cooling Plate Flow Error (X1056)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 29, 12, 'F221: TR Guage Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 18, 13, 'F046: EV2 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 18, 14, 'F047: EV2 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 5, 'F070: VV2 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 6, 'F071: VV2 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 7, 'F072: DV4 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 8, 'F073: DV4 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 10, 'F075: SRV2 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 11, 'F076: SRV2 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 12, 'F077: RV2 Open Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 13, 'F078: RV2 Close Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 14, 'F079: TP2 Start Failure'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 21, 0, 'F081: DP2 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 21, 3, 'F084: GV2 Open'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 21, 4, 'F085: GV2 Close'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 21, 10, 'F091: UL MFC1 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 21, 13, 'F094: UL MFC2 Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 27, 13, 'F190: UL Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 27, 14, 'F191: UL MFC Pressure Error'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 28, 9, 'F202: DP2 Flow Error (X1093)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 29, 6, 'F215: TP2 Flow Error (X104B)'); GO
INSERT INTO [ALARM_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 29, 14, 'F223: UL Guage Error'); GO
