INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 0, 3, 'F304: DF Discharge Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 0, 10, 'F311: DF Exis Timeout (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 18, 9, 'F642: DF Tray Position Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 18, 13, 'F646: DF Exis Timeout (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 18, 3, 'F636: EF Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 18, 5, 'F638: EF Feeding Timeout (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 20, 0, 'F665: EF Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 0, 'F601: TP1 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 5, 'F606: SRV1 Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 10, 'F611: LL Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 3, 'F620: TP1 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 8, 'F625: LL Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 13, 'F630: LL ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 20, 1, 'F666: LL Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 16, 3, 'F604: TP4 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 16, 13, 'F614: TSS Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 0, 'F617: OP Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 6, 'F623: TP4 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 11, 'F628: TSS Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 18, 0, 'F633: TSS ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 1, 'F302: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 2, 'F303: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 4, 'F305: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 5, 'F306: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 6, 'F307: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 7, 'F308: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 8, 'F309: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 11, 'F312: Temperature Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 12, 'F313: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 13, 'F314: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 14, 'F315: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 15, 'F316: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 0, 'F317: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 1, 'F318: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 2, 'F319: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 3, 'F320: LL Pump Down Timeout'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 4, 'F321: UL Pump Down Timeout'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 5, 'F322: LL, TR Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 6, 'F323: UL, TR Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 7, 'F324: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 8, 'F325: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 9, 'F326: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 10, 'F327: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 11, 'F328: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 12, 'F329: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 13, 'F330: LL MFC Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 14, 'F331: UL Exist Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 15, 'F332: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 0, 'F333: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 1, 'F334: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 2, 'F335: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 3, 'F336: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 4, 'F337: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 5, 'F338: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 6, 'F339: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 7, 'F340: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 8, 'F341: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 9, 'F342: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 10, 'F343: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 11, 'F344: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 12, 'F345: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 13, 'F346: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 14, 'F347: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 15, 'F348: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 0, 'F349: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 1, 'F350: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 2, 'F351: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 3, 'F352: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 4, 'F353: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 5, 'F354: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 6, 'F355: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 7, 'F356: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 8, 'F357: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 9, 'F358: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 10, 'F359: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 11, 'F360: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 12, 'F361: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 13, 'F362: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 14, 'F363: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 15, 'F364: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 0, 'F365: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 1, 'F366: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 2, 'F367: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 3, 'F368: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 4, 'F369: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 5, 'F370: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 6, 'F371: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 7, 'F372: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 8, 'F373: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 9, 'F374: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 10, 'F375: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 11, 'F376: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 12, 'F377: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 13, 'F378: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 14, 'F379: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 15, 'F380: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 0, 'F381: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 1, 'F382: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 2, 'F383: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 3, 'F384: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 4, 'F385: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 5, 'F386: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 6, 'F387: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 7, 'F388: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 8, 'F389: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 9, 'F390: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 10, 'F391: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 11, 'F392: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 12, 'F393: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 13, 'F394: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 14, 'F395: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 15, 'F396: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 0, 'F397: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 1, 'F398: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 2, 'F399: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 3, 'F400: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 4, 'F401: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 5, 'F402: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 6, 'F403: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 7, 'F404: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 8, 'F405: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 9, 'F406: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 10, 'F407: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 11, 'F408: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 12, 'F409: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 13, 'F410: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 14, 'F411: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 15, 'F412: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 0, 'F413: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 1, 'F414: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 2, 'F415: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 3, 'F416: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 4, 'F417: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 5, 'F418: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 6, 'F419: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 7, 'F420: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 8, 'F421: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 9, 'F422: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 10, 'F423: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 11, 'F424: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 12, 'F425: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 13, 'F426: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 14, 'F427: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 15, 'F428: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 0, 'F429: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 1, 'F430: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 2, 'F431: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 3, 'F432: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 4, 'F433: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 5, 'F434: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 6, 'F435: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 7, 'F436: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 8, 'F437: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 9, 'F438: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 10, 'F439: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 11, 'F440: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 12, 'F441: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 13, 'F442: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 14, 'F443: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 15, 'F444: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 0, 'F445: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 1, 'F446: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 2, 'F447: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 3, 'F448: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 4, 'F449: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 5, 'F450: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 6, 'F451: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 7, 'F452: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 8, 'F453: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 9, 'F454: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 10, 'F455: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 11, 'F456: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 12, 'F457: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 13, 'F458: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 14, 'F459: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 15, 'F460: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 0, 'F461: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 1, 'F462: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 2, 'F463: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 3, 'F464: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 4, 'F465: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 5, 'F466: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 6, 'F467: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 7, 'F468: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 8, 'F469: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 9, 'F470: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 10, 'F471: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 11, 'F472: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 12, 'F473: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 13, 'F474: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 14, 'F475: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 15, 'F476: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 0, 'F477: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 1, 'F478: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 2, 'F479: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 3, 'F480: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 4, 'F481: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 5, 'F482: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 6, 'F483: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 7, 'F484: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 8, 'F485: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 9, 'F486: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 10, 'F487: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 11, 'F488: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 12, 'F489: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 13, 'F490: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 14, 'F491: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 15, 'F492: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 0, 'F493: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 1, 'F494: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 2, 'F495: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 3, 'F496: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 4, 'F497: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 5, 'F498: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 6, 'F499: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 7, 'F500: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 8, 'F501: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 9, 'F502: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 10, 'F503: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 11, 'F504: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 12, 'F505: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 13, 'F506: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 14, 'F507: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 15, 'F508: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 0, 'F509: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 1, 'F510: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 2, 'F511: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 3, 'F512: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 4, 'F513: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 5, 'F514: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 6, 'F515: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 7, 'F516: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 8, 'F517: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 9, 'F518: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 10, 'F519: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 11, 'F520: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 12, 'F521: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 13, 'F522: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 14, 'F523: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 15, 'F524: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 0, 'F525: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 1, 'F526: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 2, 'F527: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 3, 'F528: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 4, 'F529: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 5, 'F530: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 6, 'F531: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 7, 'F532: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 8, 'F533: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 9, 'F534: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 10, 'F535: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 11, 'F536: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 12, 'F537: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 13, 'F538: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 14, 'F539: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 15, 'F540: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 0, 'F541: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 1, 'F542: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 2, 'F543: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 3, 'F544: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 4, 'F545: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 5, 'F546: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 6, 'F547: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 7, 'F548: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 8, 'F549: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 9, 'F550: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 10, 'F551: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 11, 'F552: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 12, 'F553: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 13, 'F554: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 14, 'F555: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 15, 'F556: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 4, 'F605: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 7, 'F608: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 8, 'F609: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 9, 'F610: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 14, 'F615: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 1, 'F618: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 2, 'F619: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 7, 'F624: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 12, 'F629: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 1, 'F634: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 2, 'F635: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 4, 'F637: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 6, 'F639: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 7, 'F640: TR2, TR3 Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 8, 'F641: TR1, TR2, TR3 Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 10, 'F643: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 11, 'F644: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 12, 'F645: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 14, 'F647: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 15, 'F648: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 0, 'F649: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 1, 'F650: PLC And GUI Connectioned Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 2, 'F651: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 3, 'F652: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 4, 'F653: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 5, 'F654: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 6, 'F655: Water temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 7, 'F656: G1 body temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 8, 'F657: G1 cooling Water (outlet) temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 9, 'F658: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 10, 'F659: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 14, 'F663: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 15, 'F664: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 7, 'F672: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 8, 'F673: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 9, 'F674: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 10, 'F675: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 11, 'F676: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 12, 'F677: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 13, 'F678: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 14, 'F679: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 15, 'F680: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 0, 'F681: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 1, 'F682: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 2, 'F683: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 3, 'F684: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 4, 'F685: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 5, 'F686: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 6, 'F687: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 7, 'F688: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 8, 'F689: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 9, 'F690: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 10, 'F691: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 11, 'F692: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 12, 'F693: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 13, 'F694: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 14, 'F695: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 15, 'F696: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 0, 'F697: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 1, 'F698: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 2, 'F699: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 3, 'F700: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 4, 'F701: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 5, 'F702: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 6, 'F703: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 7, 'F704: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 8, 'F705: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 9, 'F706: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 10, 'F707: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 11, 'F708: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 12, 'F709: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 13, 'F710: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 14, 'F711: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 15, 'F712: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 0, 'F713: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 1, 'F714: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 2, 'F715: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 3, 'F716: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 4, 'F717: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 5, 'F718: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 6, 'F719: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 7, 'F720: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 8, 'F721: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 9, 'F722: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 10, 'F723: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 11, 'F724: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 12, 'F725: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 13, 'F726: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 14, 'F727: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 15, 'F728: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 0, 'F729: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 1, 'F730: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 2, 'F731: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 3, 'F732: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 4, 'F733: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 5, 'F734: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 6, 'F735: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 7, 'F736: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 8, 'F737: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 9, 'F738: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 10, 'F739: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 11, 'F740: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 12, 'F741: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 13, 'F742: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 14, 'F743: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 15, 'F744: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 0, 'F745: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 1, 'F746: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 2, 'F747: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 3, 'F748: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 4, 'F749: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 5, 'F750: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 6, 'F751: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 7, 'F752: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 8, 'F753: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 9, 'F754: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 10, 'F755: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 11, 'F756: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 12, 'F757: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 13, 'F758: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 14, 'F759: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 15, 'F760: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 0, 'F761: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 1, 'F762: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 2, 'F763: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 3, 'F764: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 4, 'F765: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 5, 'F766: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 6, 'F767: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 7, 'F768: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 8, 'F769: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 9, 'F770: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 10, 'F771: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 11, 'F772: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 12, 'F773: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 13, 'F774: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 14, 'F775: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 15, 'F776: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 0, 'F777: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 1, 'F778: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 2, 'F779: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 3, 'F780: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 4, 'F781: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 5, 'F782: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 6, 'F783: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 7, 'F784: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 8, 'F785: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 9, 'F786: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 10, 'F787: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 11, 'F788: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 12, 'F789: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 13, 'F790: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 14, 'F791: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 15, 'F792: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 0, 'F793: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 1, 'F794: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 2, 'F795: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 3, 'F796: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 4, 'F797: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 5, 'F798: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 6, 'F799: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 7, 'F800: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 8, 'F801: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 9, 'F802: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 10, 'F803: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 11, 'F804: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 12, 'F805: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 13, 'F806: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 14, 'F807: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 15, 'F808: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 0, 'F809: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 1, 'F810: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 2, 'F811: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 3, 'F812: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 4, 'F813: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 5, 'F814: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 6, 'F815: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 7, 'F816: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 8, 'F817: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 9, 'F818: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 10, 'F819: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 11, 'F820: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 12, 'F821: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 13, 'F822: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 14, 'F823: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 15, 'F824: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 0, 'F825: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 1, 'F826: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 2, 'F827: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 3, 'F828: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 4, 'F829: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 5, 'F830: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 6, 'F831: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 7, 'F832: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 8, 'F833: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 9, 'F834: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 10, 'F835: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 11, 'F836: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 12, 'F837: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 13, 'F838: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 14, 'F839: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 15, 'F840: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 0, 'F841: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 1, 'F842: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 2, 'F843: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 3, 'F844: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 4, 'F845: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 5, 'F846: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 6, 'F847: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 7, 'F848: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 8, 'F849: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 9, 'F850: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 10, 'F851: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 11, 'F852: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 12, 'F853: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 13, 'F854: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 14, 'F855: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 15, 'F856: '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 2, 'F603: TP3 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 12, 'F613: TR Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 15, 'F616: DP3 Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 5, 'F622: TP3 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 10, 'F627: TR Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 15, 'F632: TR ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 11, 'F660: TR Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 12, 'F661: DV3 Status Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 13, 'F662: DV2 Status Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 2, 'F667: TR1 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 3, 'F668: TR2 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 4, 'F669: TR3 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 0, 0, 'F301: UL To DF Transmission Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 0, 9, 'F310: UL Exist Timeout (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 1, 'F602: TP2 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 6, 'F607: SRV2 Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 11, 'F612: UL Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 4, 'F621: TP2 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 9, 'F626: UL Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 14, 'F631: UL ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 5, 'F670: UL Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 6, 'F671: DF Exist Error (Warning Lv.2)'); GO
