INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 0, 3, 'DF Discharge Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 0, 10, 'DF Exis Timeout (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 18, 9, 'DF Tray Position Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('DF', 18, 13, 'DF Exis Timeout (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 18, 3, 'EF Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 18, 5, 'EF Feeding Timeout (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('EF', 20, 0, 'EF Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 0, 'TP1 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 5, 'SRV1 Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 16, 10, 'LL Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 3, 'TP1 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 8, 'LL Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 17, 13, 'LL ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('LL', 20, 1, 'LL Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 16, 3, 'TP4 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 16, 13, 'TSS Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 0, 'OP Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 6, 'TP4 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 17, 11, 'TSS Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('PCC', 18, 0, 'TSS ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 4, ' '); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 11, 'Temperature Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 0, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 3, 'LL Pump Down Timeout'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 4, 'UL Pump Down Timeout'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 5, 'LL, TR Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 6, 'UL, TR Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 13, 'LL MFC Pressure Error'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 14, 'UL Exist Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 1, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 2, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 3, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 4, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 5, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 6, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 7, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 8, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 9, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 10, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 11, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 12, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 13, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 14, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 15, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 16, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 17, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 7, 'TR2, TR3 Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 8, 'TR1, TR2, TR3 Tary Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 18, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 1, 'PLC And GUI Connectioned Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 6, 'Water temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 7, 'G1 body temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 8, 'G1 cooling Water (outlet) temperature abnormal (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 19, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 20, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 21, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 22, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 23, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 24, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 25, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 26, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 27, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 28, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 29, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 30, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 0, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 1, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 2, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 3, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 4, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 5, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 6, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 7, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 8, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 9, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 10, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 11, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 12, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 13, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 14, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('SYS', 31, 15, ''); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 2, 'TP3 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 12, 'TR Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 16, 15, 'DP3 Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 5, 'TP3 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 10, 'TR Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 17, 15, 'TR ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 11, 'TR Pressure Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 12, 'DV3 Status Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 19, 13, 'DV2 Status Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 2, 'TR1 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 3, 'TR2 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('TR', 20, 4, 'TR3 Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 0, 0, 'UL To DF Transmission Error (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 0, 9, 'UL Exist Timeout (Warning Lv.1)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 1, 'TP2 Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 6, 'SRV2 Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 16, 11, 'UL Vacuum Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 4, 'TP2 Pressure Er (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 9, 'UL Vent Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 17, 14, 'UL ATM Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 5, 'UL Exist Error (Warning Lv.2)'); GO
INSERT INTO [WARNING_DEF] ([EQ], [ARRAY_COUNT], [ARRAY_INDEX], [EVENT_DESC]) VALUES ('UL', 20, 6, 'DF Exist Error (Warning Lv.2)'); GO
